try {
    throw 'Boom...!';
} catch (error) {
    console.log(error);
    console.error(`Don't worry. T got you!`);

}

console.log('Continue...');
